spring:
  application:
    name: dps-kafka-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/user-created
    driver-class-name: org.postgresql.Driver
    username: usuario
    password: senha123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap:
      servers: localhost:9092
    consumer:
      group-id: consumer-group-v1
      auto-offset-reset: earliest
    topic:
      kafka-topic: "topic.user.v1"

server:
  port: 8082

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    #org.hibernate.SQL: DEBUG # Para ver os SQLs de forma mais detalhada
    #org.apache.kafka: DEBUG
    #org.springframework.kafka: DEBUG